server:
  port: 8881
spring:
  application:
    name: sales-inventory
  datasource:
    url: jdbc:postgresql://localhost:5432/sales
    password:
    username: oma
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  kafka:
    bootstrap-servers: localhost:9092
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
